addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "C4IBsX1trkAf50TvQeY0swUZbScPYqib9sgv9Mqs0zNNsitAd4y8ThkTsRhgR8DkrzVa0n6XWEZ/FtATaKLqojA37SVbpl/UsWRaU8cZ21/bjDFcNDUpwI3WFSVvS9KzWm/+4SLzAMdVBPcgNHRhlY2cg9bJ16XZG0eVJjiIzNSF1M6wRV58iQjpYgTnf79m6x1W5Y7mrrYU9Vw2PRWz+j/Th71j/zUyEnxu0rF+PEAiTVnUj+livx/QgPRu+Dm9JA8oUbAx5S+VhS8wzv3iZTQvMMRkq9YUQVjupI8Twl1ZRxUoXf6lR03hwWuznkRL97k+r0U65hAxjYfTIcDX4VdqzV5mYS2b+KPrBxt6OO9C9osaPWH4vm1VSq4r+9CpAVrm2ypQ+fm3AZdoC4jsLu9qVklXGANoyqkz7/LheXnCkoGIRLM8TmJ5w4g/eyqOwuK+/6an3o2z9yfxglW+bQDpvK686KcpGdL6ixuRdtl0w2uWxoHCr7FhZHuT+YYOEifRqoJbpJAYUFyNla0L49F2rcaB27at3xF/Kmlp9oUhQcN48JfRvfvi7kKMwgJtY0lNrg/xaNLCljOqiSUCeqKX4fwyy9SuL4689wW7fcY6/fJQFl5Nz4T+r4k+b+cqJ8V6o4Qmjqh3Atrtx6QUANIURSAcgsjl0F+FvLbE5/8="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "J6XY0EbrkIYDzbGE1Pp3tp2cLhEmxVU0qY8PmKba7iaA/GDon8nlXEaTJ55MQUZr/81/IIjGHSm8dOumU7COyrFl6tO4uAFZ0vatoqJZaocp5KW7SgemJ2VBxSYcxEZQmBh1c/+CBlAngrsb+0jFVvDt7V7HftTcu4W9ON1w1zggFofpTEK33x+QX+0yA8bYR9L5GCahy+MmZuzkW2NTYJJT8LGmDHbZQURoimIWmkVEc6RyjS7APQ2rX+FzIDFOiZqi0EFw6a9g48P3o34bA4u4nZMTJ3abIM2br5yahd5cj3vkh+szUnY1BOnouRcu7l59ZzMTYBVYEIy02xpQ6JJGFi30gELCc8tZ+oVDYR1WYbq3R3i8FOMP54FeShRIzXml4DaPwRt3grTFtmZxE9Bu8mAIJWiTLDeAHngg6ozZOYypQVXOy5QDG4lgk82vqK6GOhUGUcPxFxio76TpMFyvtuE2hXJ7MA3FBNzrgdrOaJ3mxa7oxRMPMtP8G0SV8SrSpwCKqXZNZoFszURaitA0OYT6B7LuLIkDR5VTh5YFyFrsmMdB6TA9lCdGylwQwFwJlMB6sDE2K+bAR+1sTSmWi6fWrIdBbg8PAWVjh3+x5IhwHErEBY3h2czQT1XJgULS1nTe+R6fLhm5tzTMrWdozTQXrRHZTQ/1hnbPuSE="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "L1+Hwb1fwpR/0e4obwZtMEgtqYjQbhp4IEVi2ALeMgtGXTopNSTHpoNrZA5Vn5tGFsjNc/00ADNI7cemoiTIsfiLjGkj31XpU8r8wdAvg1xAWDQaUWmzHapVgSkkN3GNb3EkPg6AXgGbxEojWONCwnhcvyLTIR/JUDrikxtDjr4c/yWQRpz+CMXDzHCIFH13XPGvjS9VrcTLVA8SzT8kHCfbT3gQ4SEebR6QLHm/V9kCYtDHO8DQ2m5skYoLQQNjihhYRqXNnuYjIAH8y2ZNc0oXcJYA2cb2GMnSDYsUTjr7EnUI9XOJlohx5eu4u4KsDD14dCZrrsvVqhrayI/5rOLYsY64OPsjPx8Q4LZJ5fu8E4s2LH8ciFJldpH/JHwtE4zpAf/+7hqMYz1gxuajr2qdpjylzHTchufWdj1bwLiZKivNoCPIxQHAcFjZyKLjzlpTxPXXswJrpPnqEaf5bOGhwV2a8mIxNAIIWOQwLLXMtIEAAUd+wfLKordSBlJATivf5mb5Ei6WSFko4yA1gNaEWv3i/PEsQoDV4njm0Pi4pGoJwvCll+Ku6o8EwcriJ43I9MGYLEsX+b965EYkxK+QAhWkTE/a/DHOZcTBuqaCMFDSIgex/FXo5c6Rs8oikuZDGKP6gbaVT1ngnQ3pzbn40Yzy+bJUpJdw782LYto="
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
