addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "vN5kOOLJTFQ2PkGsx+GErR+Xow6FH1AUj9YdUVuEq7zcNDuFP4VZUvz9OjPYZ4z1YQQXtEx1S14zKAVSTzfnRNwtO8OsLERx2R+u2z+I6pd7TcOWbPGfhU2GmtdRs9kRVzLACAG9tONTLS3TUKH1cgBEpCWjCGqGtS2IiyLevLzCCtDJw8DN8TRkhwu33fYTcltqUBUHnm3a725jT1WcnTRUhu3fK47xD/rVimGZu82g1s5ysHNoxZQE7ZcxcdyflNaAZkGZ8GhZAJeYcAh7b8wRkMS89+dJjSKcCyz84q5CtX1S7gYIYkV8CfuXqG/XWL+CZuDEuyTSsMI8r4546HWEe95CyQRyVtNvASzjXK02HLmb1Ofs5N+z/In0fjmzMIYUvUW0uYEtDn3RBwcJeHwtSFsYaN2bgA6zdQpW8+26Io0OVUTaGwIQw51w2UHhilz5vF6sbAEzU2lK3gYGTM2ZLUGHS36+rROixD4zYXdGI5/P7YUxKf1qM/HONDkjuuxjCOHGWRPCs2Uj7eGh3dzONKJj5r2LsLKYUkAkOPnEJ95wznBqdxJ9RcBEYlWhdqi/5JBWp1dVs9V+VwNMUEwA0XzE85eqjz6xNVC3RFYJJzCfPOyMflbbx7I6AM6JsKe5pX3qfPfDHcHcv/R3aPFZFo9rjafv7B4+02bVprI="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "TcFowrQfYDsfnXY5938O4w5oB+0y5bqT7SmJ9PSjZD3h3m8g+AcF19Cjw4ET7tFl31HJSNBrZM28AZBuYArwDeuOrN/UQoeJ6jVXmZg5qJ+HPr0zMcXBPLBwgDZaV5Ovhaqp89qNnYU+6QBPIf2hwtMeBtmbI/LBXT6/IGTZW0zoHdGEEeRDryFrN6jmC0P9wqsaCVE0EK7KOtcn2fqtJDA2w8crOt67ECK0Z81btfsvip+NhEmJUAV8vH5qTLPOxCpBAiQmPjBh3vGi0JN2nEcUEdrphfaDlFQCuIdg8cZwVHA3bh2eNSJgSDAHdz5lBtI4Aq07bQpeu1Ew6zkb6ByTzw67kEJz31oc+7D0QK9flOUS84egOHcAEn+xN+haeXgffLBHGD2Smrxq3WN/lw+PRosFb+O6ktUig9pFN1nJQocAa5JRzstXRn2XpZSSiMtGtxBg9l8LsbuQVQtx4D9vtYoLPgWEfto9tDR/Y0DGtdEd6CoQZyksb9LNH1m5LN8MtdtqhrSovNv4o26k2HMeVwHZtEEoLuohKv05hhZHFdBHDp8bvSLi3+Uri6wK4IjYpiHAHFXG46WaF8P4mU5mqsd1hyqRXs4H5DCxGL8DcmFF+5uFLAOJupec+jIG1yhtzoL1YxKJB9QCDWm69wZ5ZaQU5nV5bziKYfwI3Vc="

    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "Hmt8HdBLedbh+9NAek/4mT8/OK3gzWC3PqOyvOJFmXDho4J+cjxSFHgXM7COQjCgoMfs0Z+LBXH131Z0vo+mjLST1Zcwd7G6yloXK7H/FFIKdYXmK+yFyanobCLVidOSPyPfzk8zS3ohMu5/J16IVCX6AYlJjFjaEO1V0ttvUKB7FaXzzKxdF8Kfsyxicc93eyc8T1A1IsD3dhCGlhhk+kEjG7SXfBbKih1IsnPQ65voOTTuEzSwPw9oIB2KeOzuFMT6yRHY8gon5BKUjx8jfVayL8REOkh66FbJz3PGFJP5QPlhyoIETl49Rt1iU5z3mYUQwcuSHpEzrpoK/aNOkzncjAWazI7crTexQAToRwzs7JB8fCtlHHl9i2Xpd5HjqkVjK+lJ9EOjXWuKx2KzfL/o6AI//BJnH04FinYnXv3XF/5xagyTfdHzP7j5OD7O89zDMnTMH73bw8HuPmNGxhXJokwd3LGS/dTCWQpvj3xIryXF6Im2RvM9D3GLrWIvHBbXZs9maG2NblD63+aAfmw5s66j7k1KavRwrbhySslmhpfJUMyuR/BU+v1LTQOXJvdlnWaHRBtxJmbFKqAn1GynQO6QKVgKKjUKmXNscG2phpYt70FD9doP+eTjliqo7xpFJ6ytkMxo7CSVUA4xw4dKRQ/BXFm9ru2haHOUHRk="

  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
