addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "wz49Ret/bz+YQqVtsHqhJPrhca50Hto+JKVwgr6eJHlwaicSOw1tgH1BSaSJdUDk5UsaPir8rzMxNllV9a84kGJBZDbv9ZImdYkrgIy81wbeRoFLTwkL9ngakIDDs2/9L7l7zYi29vTTh/F9AFORs4RKEzshA6GQ+A+HNEPq34bdpTsqdNUpR05oKiy0olJ0d40Ul7EhkuSrgIdSDEUdAlFHA+UtI2WdQKx2mR/HLt8H8X6fr4pgYPd4csy09MX91SqiJMAfjDtSWXRccAaqdYzU93uQtgHdlT8bF0Cy7jT+ocRhWph8BkWPcu+PUSgzbUbwVH9NAujae1/sTNOCWnhpxjW5q20GcGcoLb6xAxYsJq0yUGGmQw1w11rtv6kg/EttYJNrNHo9aK+orqbNH5pv4wtU/kwnqKJ9YhlIH1UEHDrrqbMKTydr3sRy+lbbUkaDPZWrjGumieZhXbP20+HsyGh/Sol4OjIsadgRoxj+GCSoJ7BPES37C7qTvcTw8qcme7DPwh+dwzqeqSu7cpENf9clT7xswo/DvMJO6xbW4llHE0LwuAechNCt2Eii070FLtgm/PnYKOQy5npIgTKuWCN8ZpsmgOM2V0FmEUM6kJouUlRh0Imv6XQwEMcO8Aw+D/q3IRPIOqAf/ip1MDNQGBM9EM/xSk9U6Cw2tRA="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "yvjIloH2TanBm0mJtXw9gyD8l7Yu3VuDmCmWO4CMGVJM3dzXoexKxgpoyAwaLEzRIuKXpEzagj4Jyn9BMC49D/5tvlzIjqULZ7LvYmativwkbW1JuQxTuoK7J8wcsXe5qoVtYxvsCj26+sL4KDu6Nz4JFQcDowc8Rpd+ugh0RvvVes79AF6Biv0kCTP0Trc8LGiZZ3v06cGyotQ9khZcHXsNsUDaipQs/huoQbz15qu3EOisF4dd1SUx90sQVdhdvBY3LvhE/ejL5ewnssFyh8D0cIwfjwx+tycx8+lIIp88JNG5SWrHIIgnpRKCCAzP6Bh8rKi1cVfNREq09QEPa61ly6r4y4/ILm+V6j4M6sVWLnUgQaeH840aGIiL9fnjYolTP4DGZd8ZnXtAMSTtDm7QOLfn6bMwcdLxRSzbQHQGRbnQVxCSP+OYi8PTEE7A1cA62ARqQA5gFVaeAKuQgOMm7DJqRLy/nHVWT8TAvUYQ6IUdW/q1jLnGt5M/saSDOjGaj4J3pwauQ+4KJEgTZCDEOyUiNbieyk2rRuf1yvVhvP5JEYvrOWQ8+ireW+7gZZ/SjjcOJ9I6PaYPes53Bk+LXTa6LXAWElFinKlqyIyAEaemY+zLawRb/x6u8xVPQsWWaRWBwDyFvttO02ZUZRQtekZ2HUz25a2GqdAspew="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "bpaq+w3Ts54TTl4SA4gvBEzOrdU2rBdjoaggTBTurbHfN/KmuQnz2ChVHbYJDzNq1pGGIKR7jr7v2hi/ybcYFkxXFCYElk8sqrw9M0bzNcHUz+V4b9MiWCm2HhqRznWt8ei//8HhWbmGUQT5HAkOstjEs31Tnt3yv8d8hU2UJH0dQfUabz1G3qMLTYgDj5KLmQT3d3dVQVAIUjh4NlgnILe2VBJ2YcB84MBYafNATU+WrBPuTBLOqayZvTOr3zeleSSxL3nLZ4MwraGwjGCAgD2eKxfuoUkHaOGM4pjYciS8OgdsfJCm4bIWpoS0ivtVOn1DhNgC8ZogJPoiZajMfFpSL8ko3Rn1vhkW/3erf7twsdBPf+2D7xKcWQb93RdOojgpHAXBOsJQTuDL53dTVTGXLuy2z7UGGd1RLyEk2i0haMtuW5uOZHBF5zAP04C2w7DrDhR/3DqGuI0v4X7M/DBCy1PuVyJRJ9oiBQnu6a7mGinTsaNK1OV1aVLtWHhpCSfsMXo9/7TVOMoPpca9n4WZr5Yh42gUpmniiCyzVYdnBTuI0oN7FGO/5RDzyj8BfRysu7vEqttF/rqQ2RrUIrVxleLcUnPV1Z3nnPtIMlUSOGUF8mXWZyQwDtnXAosxySmAKx2m7dxCeB+Q+rhMCpYSTzbT0ucsxq2RaR11laQ="
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
