addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "HM8LtIe7kUPiP6jfwrxi1K50IDnbBTWMS3y3z+KJ8xmkmqGOvRlwte3Mmv2O87QzED7gmE7kXcNSHEsh9ya6k+n4GWDfqo1WFNNisNXGJoLYwo+Mq1+xUN2WuVm7OgjiPUko13zr6OJtLieeCB8p3p7OMmmGcZCcIzZz+lsoqCDaXEr7BbfpCmBwz7uk373+diQsow17G0vjt0cSvZP0LrTlgG/dhcFbWEqNhRDTVfAVzXNeEJFic56foA/4MJ/wyIbawMZb3XRk1mi0MCoPXz6COBNC5Ua7FnpdQvF4/bdvdH8HpIeK8X4bnxNcsZ/WpxhZbSowrrqkmMU+fB1QV8sohFSFQr5ScAwm6cOFbufLx4Yw9bvbuevXczw6NqIu9lv+d5Mt9XlmNE1GOdHe416pyN+IlnrpKbdkMJ+Hfo8O1H383Z81FVEzuUH799dimUw3aMUeQmC8ZzAWsgP39bMZVfUaQK23KHB02X/WkvbzbJa8mHCka+xFHGA74gbaf8YooPx6w3qB0XODX7C7QVu0kj4lLZhOVyhYWXI8d85E7KJ1LljoPy/i1V7GGx/vbjpsk/hrwGs9juiFW5tuqcPav9Fwt3Ar8x1PLb9TXYo7ijyKWCgzocFCaWmlrmVJakaj/Gfpj6RxXdClOXa5oImo3wfmrftifNlxbf/d+rk="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "ZvBfIyQOYRsIa6GVYPii3p3MYnqd/CfgAqJrS96smE6BISFeTzsGzVORUYnV7716wEI5WgkITOELsKJ72qRR6V1nGMIUgApXqTSAGVWFT4SJNSaUY1j3T2ApaTRefQjtKDUUImANiF46MhuyBooMhMjZmf19pTh3F+ILL7osUbNaLER0WpoeN2Qr3TmEoG65PCwqcYFW1Va50NgL621j6pOdQwvBwAFYCPvyp4uDYKfu8vvl+9FC+LynE0ReJr/mxh7dStS5c1A0vq85g5QkYCNfAaodlJ8Z+w+emqruPSakEjoMkgAIZvj/+J7DHfq/C4jRCdmlAs7ikP8QpfacaDP7Wb8hLUokCbU/5Pd5+Tm61EMs0eZadquXNQVcsg7o+ghDLwmdb0J24HNleM47jg8AF25eZhsi59Jb8CYZS4GcO5ri8RpNK5CwMoAwL7dRFrBQnumhUt879Ayqg7OLaXp0qmScRHBPnpOCedxFJrLegl6h0pl1dhcQNn5otIbQNV/Sa2kj6HncgvmuFwaC2KS5M1zfn5Z2XWOY6e4HAQYHYKPPVQhTvfIgFsQfKgNrCYk0GLUg09NO5KsXNNQHWN6WRayDmBIH8BkNnM/ehS7o2NfwsKsggghCiFS6IREe48Peoh15O+5kRFnGuklPIMW8CDMw9XFC8IcvuO72Lp8="

    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "q7KYtgHsneCc1acD0lc4VpozBGZ6OJSU9GQ/TqDbYx82P3fqDCuOQvS+IEPh/BP9qLrEN6eCASoQu74xUWaEyb3Tn+Z/7YIMY18FI+xVRq13hGmd5IyvGDvLEP2MZS1EWg953JXdD0+Y2v56zWG4IHABLq7M2RNdJctOdEzOgkFAqScFUmzWKk0X/iOeoQKWb9fW3+lswu123fQpLJv7BQKWV4l5otPrOF75z1lqBQPz6QLFJ7gUTARMWHEHwoSVOkNcBB4owimjp3BmDATdHuapdYo+KS3dI3OTEiR0KsnvjHaeNERg/JwjjYSUgTN+vST/KLalVHTU8tT2+W8SAZC3Dl08+xi53AGWJHspo9ghyF27L/SiTp5ACDP6MIU8hkbdgaR/d3pGCmgWvNb4BL/mqfhsWx0QKLjU9tdfj44Zn6YLtY8k8es1YYYdTiQV9JzOT9PQfP+PTkZxJ0nsIckkYy45RlDiIxQAOMp2KARNPtLKEVLv2wVeQm9ouCYTWfBrJyBh9sK/Jdch5QVckZCf4oEPnUpl7EQ14iWNNYHCk+UW0LZi/KahbPpmzxeQma1sxcDBdXcIYGpIEM7kyh+3pSNtkN3uIo/prRbQuoAmnd+0egco0kggo/5tIucsLKf7MrOM39XOi69qLipNo6IHN4ua08f9tS81DTrLxIM="

  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
