addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "EmrbhPlXEIbHARldcKfHY38an66njWr0gZN+0T1hshm1zweWl05fzTmcRpdGyd/rlKJDYVxT9PHQwLHdBIRnn3Gt/1dhOskjLmcGnFxIP55CPdKF4L0NFu/pCnDt/vjKrDSSQgpBBoorEvhBKHHGQhBc0jjsqlP5fNz3N/kie1mk+vwycp4KZXfwW7T3UtYLo/r5Lil+qklSRTVe67tI63HJC1GdLCAM5M9kRhg0eZoO0lLrgnH2doVC0SZr5bVyE2HhBiMoTEr1XegVGhWBV9XIuH9BKi7RYABzKxOecnyI5qjgJMAMojsXNlbR37ZPHthD0M9KIHnSoSUEoejeOV8z93p/t6sqj1qz5NHSZ96JTSGrJdk7ub4zj3GQTvJbKYgujZS0lPQoMqG1cCjg4YH7bdIzWpdp6OjtLEjQOBZzokRbWSQHb9CyTnjVevrZyoqR3aSS2wCIlKsnagnfLj01wrMT8fWKhoJWdOgYniZDAUP7gigw2JYSoffOSJEfy1qKchkz6P256Jo/QQRDWBWbAaGCJQItgU0JHhpFdBYaPvPy9ltiMf/b5YkK0h69G63kpCnMN1NDAhFmPGPr0YrJc/gTdxZwbNoziQg6mvCu6FGGgoaqAlNfebMcXmJKowJEuKD4qONj37sBIdbyH7Tae4k3zMBTLH7n69qksKY="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "DhX4rW0++CHFvw1WdRAbhZh6PsmuNXfetZEyVhFJ1uV13mVnxMI9AdhmPoDu2L68o1+IiwSJIJ26HFV6vS5FLD1mdHXhtn7Gg3652bZDN53QC2UNIbhZuPRLlEDFseVERnYbcF4rYQ91PkgjE5KxrJC7TAFrgW1kG2xnCcEQviSGk1F9eMVyyvVjOqPKOSt2F2/WA3dwBxCPVTUAE7p8uBcS/W1FVKntlwWOSHoEyILTo+HTFhubNjhn2OCZn9975TD/JXb1jdhwh7JQCVt9GhKTvcsZMG9IJz/+++nLRNsWlCBhU+MFaE3utSYkkaZncWwOhO3bvdA5WXOBEDtcG8sik8WmQMlmvN+tzAG9kXmJDWikdcu0o0h6DMUGony/eW7mLKeiRTpmSKuA+VYrw6dsA8eDL8qS2p/Yd9VZF378dOoBPre+Cw2YbM63D7nCvzVJSIlU7WTbAouwQ46wYW5rtasAomeaf/E4oDFPNVQkoKt2q7sZa9RK4OQ3xG9FhEuZA/msPaPUWHLGbrzNh+xxkGM+YjwL641Va+Ej9mCkuoAqr109y3aOnpViG9/LKaWk5z1mXDfc9aAFWL+i291jt7aJb6cql+Nh1bb3WKkmtbWquxUbnkVYGFTyOQXgf9qtRJeM43l1ZXg7xX5xm3L/EkxA5k2/Xhi++77fWYk="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install pyinvoke

install: inv docker.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "LP6PPpiLUrkTansbYh06x9I+u71YH29n1LctUH00044+Ug0JIUEpukmsj9SaVE2qXG/buidyikwH3VSv30VdhHbaFeoe1DYPRcBgOiU+haILhRsrBJBvgYdbBR3uxIk9+98sJvRHssZgUWmJB+Ytx1cU5DuESABGuTCWbE9/h4wk4kTKUzWKdNfXocigTF3tWTPxMqJIwm6jkQa0Kvytwz31kwnPBfte/GgpC2pYsFJr1dD+Rfco9xtuhyi58UfbamRcYmIr5I4ZaLf34E9HGJyCxIDtgAwGGRdAF/0Saz3QOa06mUwSk040hUHk7fBfT82j/2b0DD64LugYJuVn95FH2GYhnPRZL4YrLX19IcTfB/3GLzfy+Enqo9/0HrS7t/5NxQ96+6IKbTco7T68EkYtDbkVt89vBwI0+S/NqkcLSTf6za4nH61DQqjl8BGbtPh/FiUmyhQBGaSZPrlODvzW0DHWkmymx7LVuV3QYAwIV4O7K7dIOOXW3MBAmCFPvubdL+R/oCJ7+hF2uPySfWY7leCjYmzF9B0nDVqNc+mw4ATSyaqpvlWLWlBCSUzKr6+Pc6oN/C9FWylfkrzB+WrDvd7YIkC7WJs/q+ob3CIH9T0WQZCBkVlCQ9K0Ojw8yVel0+UUj0wgiuaDOx7urQtCjxJInh+YHvGfKJtag0Y="
  on:
    tags: true