addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "iBatj0ClUE7al3PtffXBWkjb0J83mYqiYmFNCEGBkuhyJ2tYpmMntGlJpEZGCCHGK3aLpF2qHZoiTeyckd7+OT8mNPvxPXEFCNF96ARIo6gQ1Wc4eJpFtn1Vvzjr9cGWu555NUvxwsw+wuTDwTQgziv3/siWEswylKWFzGSS7zQDYXt4UT9ttNzIawt5ZORx8caJDNr47emAxEMCIU5sR6RxhOESHNiWtIbTzMo32i+V33ofhtBsLeHLqxibUnqaralUeF911T/BPFYanKElFMK8vfUk+3GoUNtLatqK5MwgmG1CF7dIQ977VXFM3MzW0X+KdmlqF8m1dJnqsy6ltusazJBxT+7FGiX0bHQvOZfClVRL9JwBfkxaJOeQI39ckM9Nfc+Q6RB0E52cdRmIIX0PPyUbaCg4HsTvwsIMVoiIxATaHK1SX95aZv+PSIwj2gt/KIn4r3CjreY4N0dtuDOTgyu8uug2UZ/lvwDyzoUAFKoyIpq5bSo+fCj7N+90aEouRVZC/JS1CYTb4r1mLgxsMu+dZcZW0NRiaScPh2oEvhSSCvQR6XUuM+4oyJl9arM5cdtjMpPTaG48RDkU7xLZmdmALFaMMHGSSiUbMUs23b+YfP5s5r7jgemMhVV+rozzTfn85v3mfCc9eymnXqtQR9tPSJ3fKZqHjcykRro="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "D1N+lYu/u4DDllYRafdqHc1Ok9+IkaCmQWKG2/R1YJApNqOQkkQjRWZ01mIIqKAoJxpZ2O4cSha4CuNLLjzol9vCj34ZLi8Oji/drY9VdGZmv/KBf015iWprMpc6IGL33LH7uaYCOo7CbeoLWstw41HtCaGePOjfiLa059eHfivnmuvjH0S4SGSjpDIFrWfquBcoMmASr0OHM/fnlnYb8LD2AaflVqID+/P8k2gyYCWEr/Ea4Id2T5EPUyvoEq9b7H0OD6XakaGr7qcjae76g6oL948fiFLfuDD1dD2BNe+V0zMeLRLzPMPs3lfFPUBBBu1p94rba51hGOjwFMFRgngARAl84wLIEIaE5t1S2vETWN6GFkDr8MNRr+AzjPogFVcSyXf+uSAoBgc+b8ZGcXiA7Pst2MXathLw/zqpCtPiZ8b7ATkhcPgYN6lkipknXPVQeDqb68TKesiqZu5ZQZXGEUq0feqamLGrcmHLV3g0hniuooqaqFKjblA+kKCyYUrK0bLuufqF8P6h2HIp9prvW+/RZS7mhxJXPfE8QSk6rLVFMj/tLiR5+eaaFwaxgT8a3Ne6GFls0poOIMJPuhYd/zhkQ3gUVCFZLGtQUSFWa57ft+7ohaR6Ycsl1lrkC16kob5e64cvFvFx7ARPAzurTrQ0e0pl1dVwM6rs5R8="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

after_success:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
