addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "AlUzUjXD6w0SBh0GqWy/3T6veqbluPBAWoZSs3thfqAVA0+9W6LO4WfHNHw9MqrmVNqdhGMfmKYH0wYHJSak4fk/2V5qb4HU+MQFJGWom6JxCjcvtd0du7JbnKxPIHJrpd1MqPEUB/TVP4aqVWSyawIBuXePDope3/sq6TiB5R2s/7LyBrUmImdQ7jEAQy+DH37cmnQmuQFv/Vtd17A9hPPi9KYZbkpdO0Gw4soAFtUVgH+UFR1+qT4E4a/+4+OiiYpT9oiyBTJIMmKLYIf9IzWntfODOVWMK5azi64X0WcCtCo/m55vVLH/8MVbHOkaO4qwp2BOCKoD7mrjbdZztIXXi+P/JQKRkQIl9BIVJy+xQkMbj9ddb5HGUbRG1PFTq3/I/iZYFpu4n/dWizQGxD9fCojQH1HGJHbBEmnXL01qRhIKbxkkeNkDlZnWVezn+LXFPEt7ULEi/vbvhWa6xl5vgeQLALg4/DsWLQ5nDksttDZaJqwCMWLbylonrwefDwBxHSWM/Gq5CPvYq1uPemVoNRwDvf2RLX5SmB+1y1jE1SYv1EF3iAIZvDqeXysKUSkEIk2wpPUkupnrE2vbcpF1t5LenNWfC7XDVvMWcg2jPQl+feMu3CD2x7xUWIYSJd/b1omp7FNwOc163Zt0en6UMrMVEt4qfY0VVTwEUXY="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "ysSeZkm5jy4n7P7RxM0iXE7oIZvMkDJidkPCYzdRKdWCBQ/92urqYQRZzPkikdIoRhbzgTcWFqlzHxIAcSC+ol/MctkHfz22gCUZjX4yIKkTEyDAnnG5IAqF66CpgZ9E323UMLPM2zmuTm59JqTwGjBk2wUeX2vd/IHFPMlWkWxLcLt9dhOJU2Xe92XNmSSZW1s6oQnfJGp0/VNLCdFrc7qJmU+iZZ/E3+03jKRc/OHksTzMzQVDl7SNeeGpN/LgdKfdKGPSwr3Pw2QlGe7yETvIj3Om3HHuwdyrwzKaapqVQUVfHrDZgO8eQoAFAe04JaiubnnicgdF1Fbte8prfE963D+DgA76RDPz+vuf6PhNUl6OTZSFcGMFz6+Dz8R4QqxLNiWP05RSayQQr/qND9EmlAN/lu8Z0Onep93+6ULvi9uRMETUXdEPOoT3Yd1vxdj0PH6WPrOqG4k8kRlIjMqCEu1aVM0sP3IZLg6ArSA664UeyY9hp8BjVJN8muI7hc0QkW3UOiN6Lo7guL9KhjX6+QQGHmpgnPXZWFXxaif+nUPvrdNSdBcnwSpTKCUn8fVZMsTLoTZYrsSpy1kV/RlxrV0v3Y5CVuB599C5eqE3l/fKZIlpy+7oy9BVuel9AWgemnn0FdFxygFVCns16B7P/c3OByxGp4XQ3zFZS5g="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "cIK1T4QeiQ522TGOyKRHTByXq/X/5wOxS8aBjAMPneQeS0D2AKPqfuBhNPsR0H7r70o7uJeVHcOqr7zRzyv0vs4iNWRLEmb4GIHixI5wvXyEG9sNWJ1WFw1Sb4EMxH2dv60OLdPdAnpWeM0tLgHs3PBXHy3rPZce0u/PEY+kwgB8WIaKC7Nk0FIdygXr5O1bX4RTuinws/0prsUn9S6wb6cc+wiIVX1f42UIYjZee1E/tHpO4acJk2kRySImwbmb94Wk0Jjl93xlnkUz7SADq9LQOaqmW7Vs59zUvGJi8pVl4D1m/NJgWZVPUU6EvRm45q0ALDoIGv/Ub4xFcyCSNlSlMaBh1E3adLTxG5heupKk/5lgg2HzRPWUkiBwYeuR4rJyMOe0c7mA0dOuBFuhzoahhevSGqFtpC79OLBrfCe1HoJlEgzCDyk1g0/ospzaU80cO4bdWEQUdA9H/jy8dEGwNt6jP6GNXF+0rtZ4mi1xkdSJ5NSuiyNeSu+OtOLyHq5JrBKdijHeI3quVJjfZRBPAUoMec1NSyQqtXv18dynjQNI/3MzCfbMn4S8NrrC37BHUGPcRM75n4P3fRHHh9dgvdNVylShC3LgQ/H1LZolw9vEd/QSqh8E+W97OCUlYOAnfsRxZ/5HmOfNYxTE9RixT3p0Ntcr6TE/UHUg0I8="
  on:
    tags: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
