addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "LhNQxuLx7HLJu6FLCwtsKBtAH1lt0ZJeM8C3tOk5XCKsYuo3XjVB6FT5zqRv65r4kh3zPh6qaGZL+qZ4ICSjzSiwZ14/A15kiQ13WceLW/XiaVc50SOz117rpq4vT335U2gfAr1mYjeewAASrnAjsUpvlRV5imVjKFvd0OQJqxeXZgvI3XzxoMtgUWG231N5HzN2IVRrBw9SHmp39HUSNx2ARdfciV+1/DZB7wkC0JT8RInMx2pHvgdOPPYsjtu84HNq0JoAUp9fsGvIxnRvOtfQcuLV1c6qSWltPw8T1CTAQbbgkOHGuBmJDVvaGKu0t3JL5ObL7jpM2MYlHFWl6OjxtuBfdXTBUeWdzpvBar66ksXB8Jn8Egh2aZajAr7ThPmxk/DYNyI07d/FYCDkJnJbb/kZ0Mkg0P6+tL0h/pM79TUmGuZyFHnh2IuPksymf8KbJ5v+Mu+NxF37rXhJrp+7HnVuR5YSTYjcaBx/39ffy1nqhurGMETtq6gpJSMA4c1Uh4IaYwgE8rs2X62GMguIguWbl0ayYVqFqE/Z338TQH5kf6VeVAwezAed/uf7vF0QYN2VTKh/RZj0S3bUGctJRxs49624ZYlTs4i1pNCK2T4SWmgSymlK9SHHk9ujJak6ruxCA0dc3yhHgu1ze1/f3Y6a9UF8XRa2S81opQw="

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "QBpuVYPr6WrQ4Xm2P5VuSqp15TEIoj8C5OVRAESFvId6MSmcD3MDoTfnnmdITduxSBtXaUMpxAn4YQgFRTvGMS/8qqOBCDp3qEDMcBp8yeQuzXfP0xqXb61mtG6RiDqEXvxub+sFQRjZc/zzAcwqr/kkt3W7XNTy23JK+TaAo+FWuHK9kvvnz/xhlH/F7rLWPFlux+bvHi9HzOubi7h74acJr9E7Za4JrKsDHTo1YACPk/2mTQb8YdZwZ5SFmjIAfqt40uc9l+eL95+ENfR2weRf3RLnCyWX5EQKqfxh10p218Etqy87OCNtp/9Q9iVxsTqh6m+ZZxHXY74QUtVj54LBcI4Hs/LktwM5S76Cqwpl14unAXKRtp0zl6DdoKptYx8Urx9Mg7yOoOBq3FhhpK37FeG9bbP7xBYc4EKtm3DfsJdRDwkxYXbQUkxkQVCU8HMoKKfVcixqRRYt8unGLhUjCL6J+I3WjJlrFmSIEd7zs/AJ+bklU3Z7jy7XRAiNwK57pTKhia/+xH8DW75T519nCbgY3liGdeWM5mXzCJJ2MrUA6xc0/hqLG+2VCyeUYT8GsltG6F+U2UZW0XezVmDpwXCW5XKIOkSCSAn/xExC+OB+lrBqfPYt0V19HeCaIH4eEXQyexnRFCNPkqmoEfVgGxiYSAVZ3e0sIemOIbI="

    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "vKtcZdBkAhbQ45EDv9I6dPmnBga5kcNAPWhcw4GePFrE5n1D/vF7OAhh5ijyEOJMrpf4X69WPYwnfPmiGUFUe1KgVXwZ92TuKZ+P5Zq+AmF6kVEuvukKqZapI7j+RxtQgg5AoYHxfoDz1g/f/Fdie0GICZ6LEsoip3+169+T6FuDMtQn89XhhkVmAeJN4IFkvsYZvfbooHOyzQS8BHdXGL7F046f3Yqc/Mhenq/5IoYmEF08C916ciIJiUm2M7N4nvedRakufxXBUZEx3R3ede7WPczmUFOXIOdzGPCNh2n27I5pOOT6d3Mb62l2m3iA/va5ptCPUJZMVOsfg+NmJ6itVQlQTroK/ACQRvYE2SwfjK5gtbUA99RfygIbHDwsqlQtN0wWaQCSAvj6/oOqp3AlK21k/TixpHfuPgnA3RtYkXDhB15wRHuQrDekS8+kGxtpN2O2UHQnVucIp/O4NcnY2P/AMUulD1qrtYMn7/JWQGSmM0SzRcTADuWfMPaXviSqPg5puG2jKoJL0e7YOk4WjRGlQcy3H5aB/dKfke37XM+WP4GBu9RrMChsKA23XHzFHxdEU9Wr/itxw8frSx1XGhVxNA7mVzrco4Yzrwj5E0SKKeyRcOLXUe13FZfNkPA8jPu4igN4sy8TkfFjQ7pJRzBKgj4nBTtSQvyB5ns="

  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
