addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "LC2bE2TXcOEUqLEf/mqxI6ICfO8Rs2zSWt32fXCDku75yOA3sYc5/N7YoPrPYJUTalhz4c5gVmNTA0E3A7w8YpYqTKAxhsVdEbp5Ys7HEVn9OWX4j16hqOKDaz97mLkO/RwatFMv16D0Ier+8LpapCVTCVZcsgx3K4D/i4I2ygfn3AyBW/JT4Z9yzCAeE+eho3JIM5Gjsof+jKbBYuqlHGJ/wrsnKwwiJLQpV1rnglQPQHUpjOn8a9OQErag+ygFIDxAOCm1PAXtrMYp+TCjx85XdDPM9VAQuhqVuSaf13fDvUnLSXHm+3h+X+l9UfokFY3VQv3pVB+iY6imIwcUqTQu/Y6nsKAls8DNyy9laUxXbQgU3am/cB5AByzYcSxxp0pw/vaaeBfmaTXd9yAO6N+dwhm8xogp4sn8m0D4+N4TI/B56OOTDK2u2anDk6XgNTa2LvYLeEszLZxQ8rIAqofYAYshJancNvF3xBtr7enO0R6hkrTF6oT5F0bsDVokEGB3D0DEbbjq9+vLRO1FdrFo9G/frdF298m+6+TcawYYD/ImRM2g0PyRLlNZeOlyWzqwVLNxJE5mZhkoq0DePNdSi2ayoUtWEZ6OQXKKpFX1FBUHTQqk/FOoj3dx+At04YGNOl4w+NIWzEpQThVLMjFqYGWpMv47Z1KNgC8Fuy8="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "R6mJJBk5b3SWPVFLA/VuiLCcz9lWWCtlg7oP6K4tnpK7+tmt8Zlm2qEfvvQgtJqNlllXW6SoSK0Oft4EqgJ5LZHLS4k0APsM1ZqMjma+4mQir2vWfrl86pVjc2uffbc1UqI3YId6JL+rdZN49JQ0hLVRXVWBTCQW+lu9UQO9JRc3lCipdgOBsJYwwRIqLDytsYDXRJ/uX7uWj5qYB7EdwmPysHphlk/fXZ347M3A2oJbsNtTuBD12CKeRjXbZsFh/s+RCQL0dvuqSqqH4ONUWhJ5swYKhmU5Cy45zyAWeIW0DQXDRAJ3IFPIdkWCojAVsfLwjMmDE/7B/D5KKz5h5tgDRT7jp5OACr4d6D83s6mX8TvhZr8pGhDgFdv3JcoQ+8SGcL9FIpHIGVjUFn4f16gB920CTUdpw9qOLgYs08zD9fLX5Pi4r5G7NU/awzjnceSco2eJVDC/ueATE/lEQNN3pbDmPDmDhxwb3KD4za0N8hITP7o4qDzqxvxTF6NxdetCS8gKfivqPJHSumJmxwZyEG5Ihhv8qGoYKXa+LVgCMu4DGmvygW3OU+Tk/b4y0NWFRfiFq08DdVAkkW58s3yT8pjSKiS67qq9rgQPyzX/SnOwk1OPkltJo08pknZukaIoC52MltbBzgWGtzpBpOW1OndSBn8l3QxWDypK1uw="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip3 install pyinvoke

install: inv docker.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "PNnuV7aJUE4mmPLQQfSkF7bdKyGznA+Ko3K64kqXyolWPJCYgCxBbmzw/nEYLYDUSYJ2rMdKzKoULuWXK9BI5QdDi4TbeBc8JWsnO9JJqNv+y3j6eCXNEwsNAPZJPuuguba9TrC/uxaA+cw9sWz8xN0A+WLgvoeWFMFugLrrVi5J0cQbtv1AFlMgaEiA2sx+roCwQg6oBr7nznswvLA6SMYEyg0PxStLPIcAFZ66Z0vlGxz/Pav/T9mKBcUuaiWKcghlo0F1qbQN78emNeH9OPyCl8M2b8z6NTPGJ3etWyKkK058buoA1AaXDYv9UfSQeZgdMZTqGUMXmCpanLtsKZco98tY7rNwDLSgRIEj/m2IOBSGJ+4qbifGyvTnS/ky6fGEwX1v23e7aWreAUuMmCmiG6Ro8XseqsyPU9K06pqPZ4F4EVCYGLjbjz/fMWaVooSe3BkunBVaf4l9St2OkWtTy1i6Vuzy7Md+63+JEzXTZXQ5/K968CFSmOcZ9YwVRL9qo3zRkj8Qkr/ymAt21zuSAd87GZNmXlA82WDZQ8+/p7nWj1hR+znE1t4adtJx2nF3plY+8vMXDt8A/k3+x9GYQNJ8VaIMZ3tHc/I3ehg8A6m+paL1UXvQP2S9leKC8+KP/JeLrAM76QkbKL+nQAbQSj8h0AnujtFuFx/V3IY="
  on:
    tags: true