addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "nq2y3ZCqkxFG6T9iXG9/CJJKCHy9cZJHSp7+ZUHaYNVw7jU16g64JXsNMttVl3+jx8nKpVAf69HqMUC9J57eeEFD5FCoIR2O4E5/UF7hAFjVXqkxNiscZR+GKFuDZmxJKv16Ae8js08w7QpAM/6tXam/hV1gnBaC2452bMd/59MUeTrhXLy6R43wdFjhxzajBgNoYCky+LLyKnZtLgcocpBS/rEHbpdetnnyA8E4Q4wlbEadg388f86tO7wr9WzziX5XqO8L7gUTKrAmgu+VIjPpBm7LvgY5ES3InN//eutUt0cpI6P1zBRd28L4U6xeLR3Yy5A7kdkJk+0RQvJD3AesOzlJ9g6XKOyTvWppEACOH74mDR6unfZu1Ew5cjSQjJYBTlBX8fN6LJkfanQcTQZZ/goACk0B9QdrJPm8Ba/1gZAFh0V/CkgvVZ58BgFzlr13WGXjAqb4PvIIS4GMp42LAbFOdinXEXasauOhTYLu21iRUKmU8adgkuJ9TI6DgTpaUK7SGlU7IPqv32IRQk4wvizXZKaXVXaPRH/VjtAMNrHI3mjPzCFbYvkUBoo0hPtPLeRjh+5ifIwSUKcO8OtU6jFN1d53pgKwBeJMhPAicu9TjljBFgI+9FYN7fNqOtV2qv4Nzu4Ou4y0T0DjbZptnv3FbbN2yMerpVTPHi4="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "AR473x81GpGOglPOkWbGHtD8I0hjQSW/9BYqqZjN8KSydlFoa163xNmTOrPVvcRyuJvcARLotnhhiG0DB9N5cGKAmnDXBmiZy2VPH27inuCAH72R9GgScHkhQm51mjVrER5Tsju9SnkY6fXxJW6VuiDcI+cDioDVlEqHQygcFzr4+GH/1lS2g+t3h0jm/MJt5HhMhgSQMvV685ZQ/wgDH/sj6i5SK/wAqRF2XMojC4SoBf8NAML4KKMUGJ6t2bdgehGPH/kjPpJN/rw5D91quFR4SlG8iQMkVP0NaDlpbFbDjmG/96jX73Wlsf3rXGjL2n2HFWxrKtoI/8D5E/WAwJpgav5NykADBWGjObuK8mgDNqbFBFkVx60dsYw6yk1/ilxxd7CtZ/paRoBhCScZ14+yPI4lFh37bEK1fx+JHBXP5x7JDt/6RXHnGubzRD/1p2fVN93IvKWMKVRDvMtJxoqyUd2IUFwWRT3lEB7KEB9dVvKt3eUKx6xHv6oLvZnTPqKXq7HVOxQP9hePuoTDo9SvGBOjJOSeMIW3zd79bWx5Hdsw6FZaE9D9qin90Z4tsGR6BDmIz0TFgTqnVzLGpQaaHJh6FrkQlfFHh5DKDbriMvWkMlRpzyEknnRernocjdXItDg/PSagVZ8quTpwh8qftvA5a8pkLbuaydMUxb8="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "wB8EsbB/nxGi2FNrABvJh+npyF8eZwerOziH1Ght9QHLYiB0+OX6vu7OObFyziGGjMmbyQHvqHNEC7s3DW/G+hqyfVPMQ/hjPQhPfrQv+JEbI0kB10KpoeAyFms1pOIiGYqtx1mbYc7eit9MHSlbc+O/GgG9kVe2xlffvatEA78qY2H/iyhXeZEn0qPi16LDfsQu7V0LC/HHZolGooqzcC6o+z26CeAm0x2zXb2DMuHz38v06mKKDFAIPXZSzOdwhLwgEKZhl6cDZqjuve6U30Xici/DnFkVpaKB+/oJdtpzg1Mi88eLK65oUZXF+3NWZDLlmcahiJ4mxUPRuveBg9LA0uBBQ1LMW2VHGNlJiapk+t4Hh4CojXZN4BeJLMYFHApDa7DCVrL8xxUE10Z1bZe9acBgu9uOsnUX76EXeOUd8WIX5C3zUln3oBmoh+XX0RM7pMVB5PFFdqymrxFrCC6Ne3ld//Ih7yGTeD6bD/dHuRgjbeLR81rUzj6eFx33v41yTVOtiRjY07PETrQ8q4JkFiPmCaB+6JefBiR9QBDcQjLAEVDWbTlb905bfQt+RC9YLn/2Gi9bDChh4SwJIqoHq7Faq1q2hrUzrnXCBQsnGKCj2tKR3/FOZni5agCfwrTbGEyHEGNDHt1dQLB3Yvk0dBEp/QXks8t7vYOvbVA="
  on:
    tags: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
