addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "OGPtmLdnHft7q0RA5sEClai+w4AQdnQU66qlANXtBUhT2FSA+O5U6iAfzq3TZoizzmalF89yhuL56to5jZyqEHdh0+quZ8V2yCUa/g01sQUx1LZOibN9PQQ2IilYeaNqqEJy97x4L//sWPfhbvgeJvmP3IB/2jQXMG9ifAVGHsBnHAxeBgGWekHvw+tHmjCNMiKHddbDK5VbgsjklTLrFzNC/Wz2gHT/ZFYRmDdbt/lBDYH7V6NTOHir+UZF6UD2x33CgXJgapoXhM3rD637Mlg9QJMjBmcC7XfWL1FVc3QFxEB/2qfB8JpIcDuKNXuMxootbx+t/6QtiI8sb8Z6UrhMHMxdCzVAglxIkQ6/uDq8gQ9ikw6oWF2XfAdwWgNuNJp0Ob3mZd/VlZqLZOE1vlvbwHoEOf/CS8UG+EvS0VBLW5rEaH6/QD+wLTaNf60Pyn0JR8DjDkj6VTRtyCRg9RIoshMcddd1SdKoDghVH55dkEfVtNZ8aoQ05PC8yjWPQGvjn498rkrAkiDItBGeRJ5Lazd9Vd/UK/BHKo1hZix/+DFaMnAb0zgFtsLRKQ2IzZWbeoeyL2gUenuasP0VlR3c3YyDQJQbrHf1r4BJsEvcNftH6ii8/HV2DSn2U/TjrNkBRvwTO/Or2fVRS8geRA3lwxBLbz0UtwuvAGLFTCE="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "tC5pafm/K8aaXyA0dXrt4c+gKuo9aCN2/Stn3m8CYiiK811iQrsDX2pqD2rsejataNg8PeYjeGbmMwV1Sw39we+dpz7pJxz2i7f4h7+OsEGZ5BmouyKMlC9rHDXONtGV1oClMm14Pc+/cmMwVSEVzXUdviTEmxyfY5QwxxU6mATUB5sRSRFySKzMYmr6Bc8817Qviv8p1pQFrn9nMgB5cCf/KTOiG67zG5e0txZSvA0AabCjM08A3SyfzVwdoXJIoSCSG1aK3CZXczC/gtHMs9tn2TRDkcxz/6JQ5/00nzGmFSpfp5AIpOkHoulX3tm+2uHR+OoLmlBVmorRqBpvsVMW/Epc92M45FLOjAttMufAzhqbDgVrj5BERO1CqywfgRJpdVbGDZ84fqKY5S1tjV06OlCrJ6fwwG7oCCrIL0R8SMcrF+B6lLvKH2Jpb3oYYYNd1CF5D/UVZ/pMLReyVCqsnYwBxfYpasOG+KuKxqB6/kJdHlWjm9Isz0LZgQYrnaSpEBErr87oMCO91rXYbsVwsK/RRptV7+lTb4W0de3c1nlG4fyAcK4ZxpYeoqf0N3djvOa0rqIIvdiXTio5m9B9/U9e9kUpCjhN+e6VPAygQjkkPvyMy1Pu6ITAini0It7gwmHWANzvYylXo7zEe22DboQoBidSnuYrsA1UpBg="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "yMkLAr5gRN73f1zOwrL4J8WrLQuuFkdY8VVrsyDBDP34jDgzr+XzpeKs9bYQgME6VCWUf8culopX/RgOEzxe02osuLA8wuQ0Z1pOwSkP2++bzkYgh5Y9LIXzHRMgA+Kf/FCYDga1jslyO0dTctE9O2H5iQkr8q3hKn3OWXjdhv7MZQSLexBb0sndFmjv5BVNZn0bcyQbljxtxMAiddCvagUTW2aZ1cD/dav32Ga6aUJX3WdB6pge4v8qYg09hgSLpasMrvmN8fbsexGOKMauIt/yLY2kgki2y5dyNTDxcDnBrN1jMiG5zfowv48rN3kCeWG00swQNgaQ1Cuw2052XdVAU3bXql5Wo93B7OkeuBumGS4QvDzDLCPUsYNjp6EpryHQox8xKRyw6OXJG7cZA858rcdSHYvNDo6ZxB0LWjmTDwAPhBCRd+rnx1tjNZADan9+8vKpTo+KG7jRxCY96RZWmFKhXlGYKjJJzWSMM4LO2oqo7v9W2AMFs4+NtDMzx9KjGzUwcym3BJovi929dt7xv7W+mF6+GCPHFz4GDjYRJF0dwk8nxDnffSgQbqsC+St0DE06js2obcUL6MG/aKMzhNo6vXMRI26h3u8JEkDV724jCPFrQO0Vgia+3ix2HnHtnxlOPHDOdXbCiZGQCoA/dbf1OvxcsngWeHvW/Mo="
  on:
    tags: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
