addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "haCD+W0cBcmPyAgmJhEcRtif4gfNuZRcQPTHWMwuVzhyCY8svQ/nPrkOJfvzkaqg2yePQHf6ehXkhHERpbLbJ6QB8y6JeH6NhNMh4vejogXjEvAbtn4rxwymvYLfLJAlApZNdlCIFT5jcohyO+sbrjXKnE/5U6C/k4qmdvgU+9iqUJUiED6SvvEoiSH3hlodLNjhQViiVgiVanCLu93Io+dIKDh4P/wWOAnNE+LqpZZ7+WKYL1CoO8M67SmIGp74JvzqSGMxa0/JTEhUyKZnOqdvdI9CgNjnkIPOPRWzQblYVjV6kcLqGVQMyCgwxkhebcIyGfLkojBMhPZtKXDpeA3F5IMDAq1vP/OOE22R7z3FE3o8pfzFdHwqUGHj16R7wLVfpxWw0OgfiBFKx5SXXvw5rPt1mHsOr5TfCZg0HzC/HwJ8dAWFWKPayGxm5lhru1uInmZgFbgyrxTN/UM3akvFPIajZRIQB7m/ae2nJffRYaAD7sN/Egw6OvhiP4p9uLLMaTpPBUxn9sPi0deYmC9bZ4jCsEDh+Qfv/D5gyq37UdKBMfyah4iyTppiH9AqaEVvweHP5mWze3WCWKN0Q43h9qR4kRnYOBW4HqyycDChQwYcvjcG4Rbm6+5jM+oWpPZExVzWvuxADkIBA8/2UpDw12xVJgP8CJFfiFqee7w="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "d9L0bf/Rh2KkwcS2IMQ7LyNe/qdG0u+nWLPd+m69g4kY8qsolfx6Z4wMnaMTFgf5FgZ8z8drjJgkLDASyh8e0jsfxsPJWaTaiUnL19gMPHzueWwsZiTo7y7nNe1ggQEOzSAqicCQGfs1OjWOD765amdGKO+Ja6s6M7R2iJU++kurO/GtaM+xN0o6oXNbJ6WggJ7BkTvxvECZif69hnwq5Q/LQwQb2uS1C/KmIPmVxHUMc/seA/YHvRQ6FRDeZnZAI/msNHJqI1JKWl/RyBQg9yXrnlLNGZKmOOBpa2miAX7fK0vk4X2giNeMmsvUivD/1jxFVYQ43vF08VyQkNg+UN9ACtSdVeF4iwGfvEvlXwOFO5MLCC1wjyM28bn/4WCgWVyxonvdcSHfuncSBw7K1eP9WwmauR6PGemaXbs9DgIwlGwmDARbcHFtQfnmcpsL2Wm3hWFNqKf+OccE/DJ6lLuxdW0XHUzC0oVfzXhHEeE3kY32JJ4xRVS6Q+8ai0muqkl+/yyVHsS+deJkRKWvQ07A/GXXgUDMLd+MhvV4UWGTGjaddzlNkR4vMOG7W9t/VcwuT6AhobHI4BOEg/1z6ebeKMsy9ZThx6/fCFYzPWZdNG8vAof5ItL07/mRpZSg6hOnDh2psinSsS7L47djGOyN7ApOSirOZUVo3rL+Dyw="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: inv docker.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "F0qO7HQLDCZwb5OgfqYhTBJVkJ1u/6XgPI9GkBTWVWEVQSnAiyZmxKXPcqifMfNJfeWk//CqFooveqjNknbxQV/dxIQcDApUPWp9qudZDthMLTUGSmjHjTJBT5k0RU9c+w07bxnxr7oBMtgFV/pHHOhj0/D2kb06UTsckkp3mtmdxxKsAU9F4aA6p+4mPK/cmT009KgeJcpR3Unx5yrRu11M/K41yKAIiQK6Na6QiI13hHBDrNa0x4BingU2jJpsDuDtagZyoDdEkCt2unxOy1KU2Z0j2cJ0LnFQt6kYK8FvvtyUPO9MI/EOQmkALxWF2MHnql+ufWmuNDUwUmvr98i/7XL4Klk3qlmQ9UlWem3S28iXU+cbLxMnvUgzcIdFZ+JLpDFl9muMlWuBIvl18rzKo4KcJ2j6tB6OQlGS6rs04/vkqzx9LhjuK/VKUyR2X3L6IPvRqWvwzjJE1d5FcN6tF6fe68+5vTqthJtoOTYFAgUZs0qosBGMy2JuwGw6KYq8kzF8BvfGz2CUs8MEo3KGBFgcyOYDZBGS33ZEzBQNNgaPBmbLLpRQjFfv7i13ca/J05YRcBI+ZtAR5Q4HLdO+MueWqxujeAKzyXmXnR4xUs41V+MMz+i265Z8VPGbNpC1x1U1qPn24v/dbQNYKjFvgMhgJdX3oMeVSmfe2UQ="
  on:
    tags: true