addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "zU79VuocQtqOnkAIV2gIf+Ll4MCF8iJfwzvHNQFCXlDEm+kz0zYyMR/s/2W5XrfLlw+RWiCnX2ua3HFpxiLt1icrzMzRa/UeM7uCbTrp/fzqJEC8r2mqRTM1nhDufJIkcy+IlLLXgi4vtIAXoRiUa6xIohK6XRTTdOA4mNJjCBEeO0FT0Kmvtt6tssxtYQslAym0yGIphisoGKBgRchWtWTWKl0utx6t7t/vv1CQ11rVy6ODMzMPAHUGwKKVJcB4hVZsOBnr8waFKxTV/9DvBcLTh/kPBUscUcI3g6/1fQbPwEvqZyqj6QLJ+T/4zSDYigLPMPQzlDzaqPasdzNZ0JWNFksSsYbxmqO8DGggwyfz8oXRblxv5y6OI3uRJuVhfVDuDC6ptfwKmwnltHFCodCvD2RQyiD+YHAoTbDyqEnLP0G/PzhrDvU9HLrPgep9PDSlzNK4TcWe0rxCRd7o3czAk2EhKUc4OLvUS5v12DBWtKqoRy4mc94dQbtzfVb4IOnTlNsLIV0DzxYBtJ4CPtnalvAH2fu+aRhPNbBNXqi5YWZDzIkBBrdDBcaVWOP3ieMeJgIgdVJ6CXGQaQFQqWgIXR75T3riW9+PKpqqc3Hdc1wgjdhDaJlPtt1UVqnRnsFZ5u4CXz600NsJCRzkH1Hp+LujonpbefBAbb2E4N0="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "jwY25LHolu6Ei6KIv7AxIXrRT7ZHzpBNbo4VAwZ1s9RYw8Wb4QzyiQJ5QhH2w25hfw5CsXZaAUm7nIVkNJM13XNAZPy3IxFknx1Zxu75CXn/5emDt3Z+M5NefTDEJlL6U2DevMownyldRGeNs0OBjb2gDjRvoAyE8ccH+fD9+4QFZeEFhaS1aLhEFcD76WzNqY5wNxFO7MsUNesJALiFuNeZEogB21hwMNlLtJcWgj3v6uvl8btNJg9ukVTMGsccMNbIKTtqJSXX2nyXZQfwqCsutPbARRMrrUktZVOqrK76rS864sALp6CAH0Nk0Is3NgeWHsCo0JE16H63FZnfr1OAwgItZ//E5BMWsP39175tbPqp8iaHlk/Jxe5L+OsiE6v2ZufVeVjma+6RmehLtENdwKDu4joYUbqr35HVT4xBTrl4FVef+ffc65Z+LgJ+VA3Cflbe9ITr+L9TxhUCQD69ojM55OEAT6FO4NcBuQ50YuO/NpbU2hXmK6pmL2stinXzBBk3EXqJlv25RbzYEuVRY7mjeWU5OIgnmZaka25YAqIz0ThfFUht3rBOWST25spzOkICdmtGt3AOy3O+SPs+bVzBVycPN4kzZ6Y1M5DsGkBXhVzsQLnIeOyF8ww7/fBuGP/vsnY89SskZvxMDX7J9ov3Ch/7N+eayU0ezqU="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "UEJw5B4M49PUM8GRd1jXyKDpRYZ4+73+c0cvDXC6e/eUPNVqNiGEghghhQHOesmqBqeZGbcyrYS1UtPUKdvXz96VV6WehIsypYd3c0lM7CQrUB36COl16J2K2A69ENjRBmJnnmNrds8LFUeGkAd2x3G4h9gHFE2p5Z2n0GQCROaWM4wLXc2o/ZWK/D2bBcoaEpK8UwdbWg7xQOokAB+gero3rRvUji7oLcb3TWkM3KXjWmI7G7kEZp2EgvjZqnIoLjH/Y4jK7bWgDnXfB+N0Esh92WQqxMUouITIb9iEyMeD5DgUdIY5+sQ60fR5E0smfU9dTI49uycHj3FujvyYlbqIZge/BEuBs9qD5fsWl3SIQZ9FO5Zl75Fi44gleraS2G+oGssEEt3hNxsze19bAhnfr+G8nG/PoqKzL3fAiTD3cbi+hjCKRl0FNhoxMCTlsY2BQSr2x5wBOzGNABCW4UDCBZv+Ip5TyfcHiatrVlYVZJM66t2OwAwCgEk2rqU6YxZCFVtch1FZ4P1C5LDm5B4PDQYZPfKmk0gLfD3IAjyaY8upR+OKJ0jSvk3F/bUj8Q6QqsA71q602qh1LF5zz3qTnx/9ulXrd1hOXaU0WptzgE1lptjtF/kMuF/SuK+tcf5oJq7QEqQ/JFCt01p16i5nQHVPfDdxbeI6d9ENjT0="
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
