addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: <Command 'travis encrypt --no-interactive "DOCKER_PASS=6kT9CnyRacARkgz*}Hny.T3@TUDEQz"'>
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: <Command 'travis encrypt --no-interactive "valuphone:Csf6WHa2TfyPFUrWtkmMeb4u"'>
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: <Command 'travis encrypt --no-interactive "GBsrJpyjY8J39mGVwdjo"'>
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
