addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=joeblackwaslike
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=joeblackwaslike
  # DOCKER_PASS
  - secure: "rBexUFkq+elnLjGQ/Xln6gkfsbeDu5ohBSPdbiaL/lVdWWmNVgdhN8K0+usyMQd9IIDCtBdpYeetHnvzqxKFv3XYgybZoVLLHb0/JlooSb2ioGRNhYSN/GrAlsn7tenivz4und/YSSBCilSqU/np7TcjurOEVFESCfDRhboDHbCGECAe5PBa7xjrngt58buxsvXBl4FE20fw5vFD36nPfMxng6wHlMkfh3mbjVCxnb0naZq5PARN2zcbaxJae/144Ddot32B4mt3mmOSrxGimrUL74AiUgzNDj2KzViWTlb7zmQvZM9jpQqtFMrrnE3/xWTVoRomOrRAdEbBRU8+5EY07YcjNde9KTroSwrYUO8EOzo7dkpPX/AMK6Mv3ByLhKAIW0XtbaWyT5fuv1yc/zJL9OU44n0Xqu02WDqTRc+PFdExdG88R3ySLt4EQ2YnY1OQaqI+ZQ+LKnU+Bxa6EkmdktKho+7ElsZgXeOFBvCVgWKI6fQgbg3cQxJXrlRxQjZS6/6/O8NGmZXFMDmCVhEwVRdQLjxKY02dkKHbpiqyYC/uGi7zFt7jLcHZZ107Hq+T7DJMZ2KscRxtOKRbyFnXaP5rE9qAKt1M/89W6V7y+I3Ng+x5tZvc8CYns08XFmyhs0qCiYXChw5yzul+LVxNAAzm4M7doBpxHKy4K0I="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "xCvoGiCFb+tag0t/fZTNZX1onx6JImDJJuwn/DfRuGKejgUv6NObCXqLnk5u3vYlVMvll6mlcxY322LtcyYNiJ/r5I23pOyIPlafG1o/0SE+vVoUGweXlCB828/NBT3Su158k3SlwmumJS9MdUFYs1aaWI+WnOBaTktENqArTiEZlYac2ufqqNx4lzAOv42wXH15TIx4w+ax67SkyfMrMq09tH9mPciKkyyRjqOLUqxEyKNdORAKnDr+CQLm8AX/jGOx6b+OF09XUxZHugraITd4D07NH7Bvbko3zFJFvSpaRee7cFlM0lDsc8mqcduVWC3Zw1GS1Szwa1h0K4uFAeYKWEYSxS780mFFO27VSpMsVnTcHjFsTZftwYpC2V8SJ+QibDT7RUWcVV4mi1wQwibEyWZbDrVUEyo+XACbhNvKFLjTzTKLgneo/Acol8v+fZNrOt6gMzt6CIqWAqG0SHZGK5ZHc+rkdWYfyiCSk8Ha4LdFN0XWuVfh/5IxbowiXzK2I6NRaohkmoeoo6Hlp4Vepbdcgk0urIiaMO2Lj4AM4WQmxiwEJcXKdwtZG4pRSDn2kQdQiCp6kYF0ps53z6aF0cSaTgI5hDpT+D4Kx0JBzdYWkyJID/d0NOD6oODr/BHVZlOcrUcZoDg4qKnoXvPdf9MLe8IMAdUvgn/9z2Q="
    on_success: always
    on_failure: always
before_install:
- source scripts/ci/environment.sh
- pip install invoke

install: pip install -e .

script: inv test

deploy:
  provider: pypi
  user: joeblackwaslike
  password:
    secure: "lJRUZGTjmkEhbs+aAKu7yV5lwmqVsxkhypOGlTnuSqzrmy72t9a307gvSurexsIGElh3oBLvQFDHnr42hKAtlkRoa/coWp2FlNleTlG7UXuZPbKADC8rvSP6zB2j8gCobPCbsayLQS86UGroetH29ti7uKt4qYABzbyRWPoIhziIwf57GHyyO1dverzAr8iLgms0bgX2bXsfr/9jmjAZcX5tTuQK8fj7r7cVci/ih9JKDpimdN6SL0ffYG7fZ57JGWZredp2+1eDslNWH3PZ/fai76fsY7aK4eqkmC/S5DPloHrl6D0ly6ihgcDJv8Ru4OWnC6wfdsqhdFsrvn6J+juWPg2Cz0/WDBfbEWO2RueRV186dCevzq22m117A2nTUtrX3xZybBG3m33a2T3bj+CEPANbRG11D/hK0nu94w9FFFuNaOuC7NlluIuh23Ux6z2FdAV2XJ4lQHTXjuK4Ks37toMgAgQ7fvBRmlFJf1S8dNjMdAlI4oVD6dZaiNQGHt9cUlWOuj7wTNpNXbX/eMAXfLnTIbLthtaBpBH8d+MD5syvjDBN+TQMLIUYy61WrGvAGu86VWfQJQxnDqQkwKYiGDW4MOVjamBirkh87O+nsrs9qeQP8t8tyRXYqD76fELblCs1fy8Kb6VkwUR/BvFrlntnNbCL8R6iz7QH0Xc="
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- docker build -t $DOCKER_ORG/tmpld:latest --force-rm .
- ci-tag-build
- hub-push
- hub-update-readme
